version: "3.7"
services:
    redis-server:
        image: redis
        container_name: redis-server

    api:
        build: .
        container_name: api
        restart: unless-stopped
        ports:
            - 7500:7500
        #depends_on:
        #    - redis
        #links:
        #    - redis
