version: "2"
services:
    redis:
        image: redis
        container_name: cache
        ports:
            - 6379:6379
        networks:
            - front
    app:
        # some definitions
        build: ./backend
        links:
            - redis
        ports:
            - 7500:7500
        networks:
            - front
networks:
    front:
        # use the bridge driver, but enable IPv6
        driver: bridge
