version: "2"
services:
    api:
        # some definitions
        build: ./backend
        container_name: api
        ports:
            - 7500:7500

    client:
        build: ./frontend
        container_name: client
        ports:
            - 3000:3000
        depends_on:
            - api

    admin:
        build: ./frontend
        container_name: admin
        ports:
            - 3001:3001
        depends_on:
            - api

    nginx:
        depends_on:
            - api
            - client
            - admin
        restart: always
        build: ./nginx
        ports:
            - "80:80"
